window.SPECIMENS = [
  {
    id: "pf-rings",
    name: "Plasmodium falciparum ring forms",
    category: "parasitology",
    difficulty: 4,
    stain: "Giemsa / hematoxylin",
    mag: "1000× oil",
    file: "Plasmodium falciparum (malaria) parasite in blood.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Babesia microti", "Howell–Jolly bodies", "Platelets overlying RBCs"],
    blurb: "Delicate ring trophozoites inside erythrocytes, often with double chromatin dots and multiply infected cells. No Schüffner stippling. The professional trap is Babesia, which can also make small rings but may show tetrads."
  },
  {
    id: "pf-gam",
    name: "Plasmodium falciparum gametocyte",
    category: "parasitology",
    difficulty: 3,
    stain: "Giemsa",
    mag: "1000× oil",
    file: "Plasmodium falciparum gametocyte.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Microfilaria fragment", "Trypanosoma cruzi", "Plasmodium vivax gametocyte"],
    blurb: "The crescent or banana-shaped gametocyte is pathognomonic for P. falciparum. Other malaria species make round gametocytes. Do not confuse a folded crescent with a trypanosome kinetoplast."
  },
  {
    id: "p-vivax",
    name: "Plasmodium vivax",
    category: "parasitology",
    difficulty: 4,
    stain: "Giemsa",
    mag: "1000× oil",
    file: "Plasmodium vivax 01.png",
    credit: "CDC / Wikimedia Commons, public domain",
    lookalikes: ["Plasmodium ovale", "Plasmodium falciparum rings", "Babesia microti"],
    blurb: "Large ameboid trophozoites in enlarged, pale RBCs with Schüffner dots. Ovale can look similar but typically infects oval, fimbriated cells and stays more compact."
  },
  {
    id: "p-malariae",
    name: "Plasmodium malariae",
    category: "parasitology",
    difficulty: 5,
    stain: "Giemsa",
    mag: "1000× oil",
    file: "Plasmodium malariae 01.png",
    credit: "CDC / Wikimedia Commons, public domain",
    lookalikes: ["Plasmodium falciparum", "Plasmodium knowlesi", "Babesia microti"],
    blurb: "Band-form trophozoites in normal-sized RBCs, with coarse pigment. Knowlesi is the modern lookalike in Southeast Asia and can be indistinguishable without PCR."
  },
  {
    id: "babesia",
    name: "Babesia microti",
    category: "parasitology",
    difficulty: 5,
    stain: "Giemsa",
    mag: "1000× oil",
    file: "Blood smear of Babesia microti, original.png",
    credit: "Wikimedia Commons",
    lookalikes: ["Plasmodium falciparum rings", "Howell–Jolly bodies", "Bartonella bacilliformis"],
    blurb: "Small intraerythrocytic rings, sometimes tetrads (Maltese cross), no hemozoin pigment, and no travel-to-tropics story required. The Maltese cross is diagnostic when present; most fields only show rings."
  },
  {
    id: "t-cruzi",
    name: "Trypanosoma cruzi",
    category: "parasitology",
    difficulty: 4,
    stain: "Giemsa",
    mag: "1000× oil",
    file: "Trypanosoma cruzi in a blood smear.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Trypanosoma brucei", "Borrelia recurrentis", "Microfilaria"],
    blurb: "C-shaped trypomastigotes with a large subterminal kinetoplast. T. brucei is usually more slender with a smaller kinetoplast. Spirochetes lack a nucleus-kinetoplast pair."
  },
  {
    id: "t-brucei",
    name: "Trypanosoma brucei",
    category: "parasitology",
    difficulty: 4,
    stain: "Giemsa",
    mag: "1000× oil",
    file: "11820 lores.jpg",
    credit: "CDC / Wikimedia Commons, public domain",
    lookalikes: ["Trypanosoma cruzi", "Borrelia spp.", "Microfilaria"],
    blurb: "African trypanosomes in blood: elongated trypomastigotes with a small kinetoplast and undulating membrane. Geography and a chancre or Winterbottom sign help, but the kinetoplast size separates it from T. cruzi."
  },
  {
    id: "leishmania",
    name: "Leishmania donovani amastigotes",
    category: "parasitology",
    difficulty: 5,
    stain: "Giemsa",
    mag: "1000× oil",
    file: "Extracellular Amastigotes of Leishmania donovani in Giemsa stained smear.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Histoplasma capsulatum", "Toxoplasma gondii", "Trypanosoma cruzi amastigotes"],
    blurb: "2–4 µm amastigotes with a nucleus and rod-shaped kinetoplast. Histoplasma is similar size but GMS-positive, lacks a kinetoplast, and often shows a narrow-based bud. This is a classic boards-level distinction."
  },
  {
    id: "giardia",
    name: "Giardia lamblia",
    category: "parasitology",
    difficulty: 2,
    stain: "Bright-field / trichrome",
    mag: "400–1000×",
    file: "Giardia.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Trichomonas vaginalis", "Chilomastix mesnili", "Dientamoeba fragilis"],
    blurb: "Owl-face trophozoites with two nuclei, median bodies, and flagella, or oval cysts with four nuclei. Trichomonas has one nucleus and no cyst stage. Chilomastix has a single nucleus and a spiral groove."
  },
  {
    id: "e-histolytica",
    name: "Entamoeba histolytica trophozoite",
    category: "parasitology",
    difficulty: 4,
    stain: "Trichrome / iodine",
    mag: "1000× oil",
    file: "Entamoeba histolytica trophozoite.png",
    credit: "Wikimedia Commons",
    lookalikes: ["Entamoeba coli", "Macrophage in stool", "Iodamoeba bütschlii"],
    blurb: "Ameba with ingested RBCs and a small central karyosome. E. coli has a larger, eccentric karyosome and coarser chromatin. Macrophages can swallow RBCs but lack a true karyosome."
  },
  {
    id: "cryptosporidium",
    name: "Cryptosporidium oocysts",
    category: "parasitology",
    difficulty: 4,
    stain: "Modified acid-fast",
    mag: "1000× oil",
    file: "Cryptosporidium DPDxCrypto oo AF.JPG",
    credit: "CDC DPDx / Wikimedia Commons, public domain",
    lookalikes: ["Cyclospora cayetanensis", "Cystoisospora belli", "Yeast in stool"],
    blurb: "4–6 µm acid-fast spheres. Cyclospora is larger (8–10 µm) and stains variably. Cystoisospora is much larger and often oval. Size plus acid-fastness is the whole game."
  },
  {
    id: "toxoplasma",
    name: "Toxoplasma gondii tachyzoites",
    category: "parasitology",
    difficulty: 4,
    stain: "Giemsa",
    mag: "1000× oil",
    file: "Toxoplasma gondii tachy.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Leishmania amastigotes", "Histoplasma capsulatum", "Trypanosoma cruzi amastigotes"],
    blurb: "Crescentic tachyzoites with a central nucleus, no kinetoplast. In tissue they form cysts with bradyzoites. Leishmania always carries a kinetoplast; Histoplasma buds and stains with GMS."
  },
  {
    id: "s-haematobium",
    name: "Schistosoma haematobium egg",
    category: "parasitology",
    difficulty: 3,
    stain: "Unstained wet mount",
    mag: "100–400×",
    file: "Schistosoma haematobium egg.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Schistosoma mansoni egg", "Schistosoma japonicum egg", "Hookworm egg"],
    blurb: "Large oval egg with a terminal spine, classically in urine. Mansoni has a lateral spine; japonicum is smaller and more rounded with a tiny knob. Hookworm eggs have a thin shell and no spine."
  },
  {
    id: "ascaris",
    name: "Ascaris lumbricoides egg",
    category: "parasitology",
    difficulty: 2,
    stain: "Unstained wet mount",
    mag: "400×",
    file: "Ascaris lumbricoides egg.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Hookworm egg", "Trichuris trichiura egg", "Taenia egg"],
    blurb: "Fertile eggs are thick-shelled and mammillated, 55–75 µm, with a round-oval contour. Decorticated eggs lose the albuminous coat and can fool people into calling them hookworm."
  },
  {
    id: "trichuris",
    name: "Trichuris trichiura egg",
    category: "parasitology",
    difficulty: 2,
    stain: "Unstained wet mount",
    mag: "400×",
    file: "Trichuris egg.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Enterobius vermicularis egg", "Hookworm egg", "Capillaria philippinensis egg"],
    blurb: "Barrel-shaped egg with bipolar plugs. Pinworm is flattened on one side. Capillaria is a genuine lookalike but smaller, with striated shells and less prominent plugs."
  },
  {
    id: "hookworm",
    name: "Hookworm egg",
    category: "parasitology",
    difficulty: 3,
    stain: "Unstained wet mount",
    mag: "400×",
    file: "Hookworm egg.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Strongyloides egg", "Ascaris (decorticated)", "Trichostrongylus egg"],
    blurb: "Thin-shelled oval egg with a 4–8 cell morula in fresh stool. Species (Necator vs Ancylostoma) cannot be told from the egg. Strongyloides usually hatches in the gut, so eggs in stool are uncommon."
  },
  {
    id: "pinworm",
    name: "Enterobius vermicularis egg",
    category: "parasitology",
    difficulty: 2,
    stain: "Scotch tape prep",
    mag: "400×",
    file: "Enterobius vermicularis egg.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Trichuris trichiura egg", "Hookworm egg", "Pollen grain"],
    blurb: "Colorless, planoconvex egg: flattened on one side, D-shaped. Found on perianal tape, not reliably in stool. Pollen and tape artifacts are the usual false positives."
  },
  {
    id: "strongyloides",
    name: "Strongyloides stercoralis larva",
    category: "parasitology",
    difficulty: 4,
    stain: "Wet mount / iodine",
    mag: "100–400×",
    file: "Strongyloides stercoralis.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Hookworm rhabditiform larva", "Enterobius adult fragment", "Free-living nematode"],
    blurb: "Rhabditiform larvae in stool with a short buccal canal and prominent genital primordium. Hookworm rhabditiform larvae have a long buccal canal. This distinction matters in hyperinfection."
  },
  {
    id: "trichinella",
    name: "Trichinella spiralis in muscle",
    category: "parasitology",
    difficulty: 3,
    stain: "H&E",
    mag: "100–400×",
    file: "Trichinella spiralis.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Sarcocystis in muscle", "Toxoplasma tissue cyst", "Artifact / folded fiber"],
    blurb: "Coiled larva inside a nurse-cell cyst in skeletal muscle. Sarcocystis cysts are larger, septate, and lined by a thicker wall. Clinical cue: myalgias after undercooked pork or game."
  },
  {
    id: "taenia",
    name: "Taenia egg",
    category: "parasitology",
    difficulty: 3,
    stain: "Unstained wet mount",
    mag: "400×",
    file: "Taenia egg.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Hymenolepis nana egg", "Ascaris lumbricoides egg", "Pollen grain"],
    blurb: "Spherical, brown, radially striated embryophore with a hexacanth embryo. T. solium and T. saginata eggs are indistinguishable. Hymenolepis is smaller and has polar filaments."
  },
  {
    id: "microfilaria",
    name: "Microfilaria",
    category: "parasitology",
    difficulty: 4,
    stain: "Giemsa",
    mag: "100–400×",
    file: "Microfilaria.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Trypanosoma brucei", "Borrelia spp.", "Cotton fiber artifact"],
    blurb: "Sheathed or unsheathed nematode larvae in blood. Speciation uses sheath, nuclei to the tail tip, and periodicity. Fibers lack nuclei; trypanosomes are much smaller and have a kinetoplast."
  },
  {
    id: "tb",
    name: "Mycobacterium tuberculosis (AFB)",
    category: "microbiology",
    difficulty: 3,
    stain: "Ziehl–Neelsen",
    mag: "1000× oil",
    file: "Mycobacterium tuberculosis Ziehl-Neelsen stain.jpg",
    credit: "Wikimedia Commons, public domain",
    lookalikes: ["Nocardia (partially acid-fast)", "Mycobacterium avium complex", "Artifact / stain precipitate"],
    blurb: "Beaded red rods against a blue background. Species cannot be told from morphology. Nocardia is branching and only partially acid-fast with a weaker decolorizer."
  },
  {
    id: "s-pneumoniae",
    name: "Streptococcus pneumoniae",
    category: "microbiology",
    difficulty: 3,
    stain: "Gram stain",
    mag: "1000× oil",
    file: "Streptococcus pneumoniae.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Viridans streptococci", "Enterococcus", "Listeria monocytogenes"],
    blurb: "Gram-positive lancet-shaped diplococci, often with a clear capsule. Viridans strep are in chains and lack the lancet pair. Clinical context (lobar pneumonia, rusty sputum) still helps."
  },
  {
    id: "s-aureus",
    name: "Staphylococcus aureus",
    category: "microbiology",
    difficulty: 2,
    stain: "Gram stain",
    mag: "1000× oil",
    file: "Staphylococcus aureus Gram.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Coagulase-negative staphylococci", "Micrococcus", "Peptostreptococcus"],
    blurb: "Gram-positive cocci in grape-like clusters. You cannot speciate from the smear; clusters vs chains is the useful split. Micrococcus is usually tetrads and a contaminant story."
  },
  {
    id: "n-gonorrhoeae",
    name: "Neisseria gonorrhoeae",
    category: "microbiology",
    difficulty: 3,
    stain: "Gram stain",
    mag: "1000× oil",
    file: "Neisseria gonorrhoeae.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Neisseria meningitidis", "Moraxella catarrhalis", "Acinetobacter"],
    blurb: "Kidney-bean Gram-negative diplococci, many inside neutrophils. In a urethral smear from a symptomatic man this is highly predictive. Meningococcus and Moraxella look the same on Gram."
  },
  {
    id: "c-tetani",
    name: "Clostridium tetani",
    category: "microbiology",
    difficulty: 3,
    stain: "Gram stain",
    mag: "1000× oil",
    file: "Clostridium tetani.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Clostridium botulinum", "Clostridioides difficile", "Bacillus spp."],
    blurb: "Slender Gram-positive rods with terminal spores — the drumstick or tennis-racket form. Other clostridia spore, but the strictly terminal swollen spore is the classic tetani look."
  },
  {
    id: "h-pylori",
    name: "Helicobacter pylori",
    category: "microbiology",
    difficulty: 3,
    stain: "Giemsa / H&E / silver",
    mag: "400–1000×",
    file: "Helicobacter pylori.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Campylobacter", "Contaminating oral flora", "Mucus strands"],
    blurb: "Curved Gram-negative rods in the gastric mucus layer, often in pairs or gull-wing forms. IHC or Giemsa makes them pop. Do not overcall debris in the mucus."
  },
  {
    id: "candida",
    name: "Candida albicans",
    category: "microbiology",
    difficulty: 2,
    stain: "Gram / KOH / PAS",
    mag: "400–1000×",
    file: "Candida albicans.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Aspergillus hyphae", "Trichosporon", "Artifact / fiber"],
    blurb: "Budding yeasts with pseudohyphae; true hyphae can appear in tissue. Aspergillus has septate hyphae with 45° branching and no yeast forms. Species needs culture or MALDI."
  },
  {
    id: "aspergillus",
    name: "Aspergillus fumigatus",
    category: "microbiology",
    difficulty: 3,
    stain: "GMS / PAS / lactophenol",
    mag: "400×",
    file: "Aspergillus fumigatus.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Fusarium", "Mucorales", "Candida hyphae"],
    blurb: "Septate hyphae branching at acute angles; fruiting heads if a cavity communicates with air. Mucorales are broader, ribbon-like, and pauci-septate. Fusarium is the histologic twin."
  },
  {
    id: "c-neoformans",
    name: "Cryptococcus neoformans",
    category: "microbiology",
    difficulty: 3,
    stain: "India ink / mucicarmine / GMS",
    mag: "400–1000×",
    file: "Cryptococcus neoformans.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Candida in CSF", "Artifact in India ink", "Blastomyces dermatitidis"],
    blurb: "Narrow-based budding yeast with a thick capsule that clears on India ink and stains red with mucicarmine. Blastomyces is larger with broad-based budding and no true capsule."
  },
  {
    id: "blastomyces",
    name: "Blastomyces dermatitidis",
    category: "microbiology",
    difficulty: 4,
    stain: "GMS / PAS / KOH",
    mag: "400–1000×",
    file: "Blastomyces dermatitidis.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Cryptococcus neoformans", "Coccidioides endospores", "Paracoccidioides brasiliensis"],
    blurb: "8–15 µm thick-walled yeast with broad-based budding. The 'double contour' wall is the giveaway. Paracoccidioides makes a pilot-wheel of multiple narrow buds."
  },
  {
    id: "coccidioides",
    name: "Coccidioides immitis/posadasii",
    category: "microbiology",
    difficulty: 4,
    stain: "H&E / GMS",
    mag: "200–400×",
    file: "Coccidioides immitis.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Rhinosporidium seeberi", "Empty spherule artifact", "Blastomyces dermatitidis"],
    blurb: "Large spherules packed with endospores. No budding. Rhinosporidium spherules are bigger and sit in mucosa of a different epidemiology. Empty spherules get overcalled constantly."
  },
  {
    id: "pneumocystis",
    name: "Pneumocystis jirovecii",
    category: "microbiology",
    difficulty: 4,
    stain: "GMS / toluidine blue",
    mag: "400–1000×",
    file: "Pneumocystis.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Histoplasma capsulatum", "Candida glabrata", "Stain precipitate"],
    blurb: "Cup-shaped or crushed-ping-pong-ball cysts in alveolar casts. Does not bud. Histoplasma is intracellular and buds. GMS of a foamy alveolar exudate is the classic scene."
  },
  {
    id: "cmv",
    name: "Cytomegalovirus inclusions",
    category: "microbiology",
    difficulty: 3,
    stain: "H&E",
    mag: "400×",
    file: "Cytomegalovirus infection.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["HSV / VZV inclusions", "Reactive pneumocyte atypia", "Adenovirus smudge cells"],
    blurb: "Owl-eye nuclear inclusions and granular cytoplasmic inclusions in enlarged cells. HSV has molding, margination, and multinucleation without the huge cytoplasm. IHC settles close calls."
  },
  {
    id: "histoplasma",
    name: "Histoplasma capsulatum",
    category: "microbiology",
    difficulty: 5,
    stain: "GMS",
    mag: "400–1000×",
    file: "Histopathology of Histoplasma capsulatum, GMS stain.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Leishmania amastigotes", "Cryptococcus (capsule-deficient)", "Candida glabrata"],
    blurb: "Tiny 2–4 µm intracellular yeasts with narrow-based budding, GMS-positive. No kinetoplast — that is how you beat Leishmania. Capsule-deficient crypto is larger and mucicarmine may still help."
  },
  {
    id: "sickle",
    name: "Sickle cells",
    category: "hematology",
    difficulty: 2,
    stain: "Wright–Giemsa",
    mag: "400–1000×",
    file: "Sickle cell anemia smear.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Hemoglobin SC disease", "Bite cells / oxidant injury", "Artifact from old smear"],
    blurb: "Elongated, pointed drepanocytes plus targets and polychromasia. SC disease shows fatter boats and many targets. True sickles should be irrevocably pointed, not just elongated."
  },
  {
    id: "aml",
    name: "Acute myeloid leukemia",
    category: "hematology",
    difficulty: 4,
    stain: "Wright–Giemsa",
    mag: "1000× oil",
    file: "AML-M2.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Acute lymphoblastic leukemia", "Reactive left shift", "CML blast crisis"],
    blurb: "Circulating myeloblasts with open chromatin, nucleoli, and often granules or Auer rods. ALL blasts are usually smaller with coarser chromatin and no Auer rods. Flow and genetics are required."
  },
  {
    id: "cll",
    name: "Chronic lymphocytic leukemia",
    category: "hematology",
    difficulty: 3,
    stain: "Wright–Giemsa",
    mag: "1000× oil",
    file: "Chronic lymphocytic leukemia.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Mantle cell leukemia", "Follicular lymphoma in blood", "Reactive lymphocytosis"],
    blurb: "Small mature-looking lymphocytes with clumped chromatin and smudge cells. Mantle cell can mimic this exactly — cyclin D1 / SOX11 save you. Reactive lymphs are more pleomorphic."
  },
  {
    id: "cml",
    name: "Chronic myeloid leukemia",
    category: "hematology",
    difficulty: 4,
    stain: "Wright–Giemsa",
    mag: "400–1000×",
    file: "Chronic Myeloid Leukemia smear 2009-04-09.JPG",
    credit: "Wikimedia Commons",
    lookalikes: ["Leukemoid reaction", "CMML", "Polycythemia vera with left shift"],
    blurb: "Left-shifted granulocytes from blasts to segs, basophilia, and few dysplastic monocytes. A leukemoid reaction lacks basophilia and has a high LAP score. Always think BCR::ABL1."
  },
  {
    id: "neutrophil",
    name: "Neutrophil",
    category: "hematology",
    difficulty: 1,
    stain: "Wright–Giemsa",
    mag: "1000× oil",
    file: "Neutrophil.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Band neutrophil", "Monocyte", "Pelger–Huët cell"],
    blurb: "Multilobed nucleus and pale granules. Bands have an unsegmented C-shaped nucleus. Pelger–Huët cells are hyposegmented and can be inherited or acquired in myeloid neoplasms."
  },
  {
    id: "eosinophil",
    name: "Eosinophil",
    category: "hematology",
    difficulty: 1,
    stain: "Wright–Giemsa",
    mag: "1000× oil",
    file: "Eosinophil.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Neutrophil with toxic granules", "Basophil", "Mast cell"],
    blurb: "Bilobed nucleus buried in large orange-red granules. Toxic neutrophils have finer, darker granules and a different nucleus. Mast cells are tissue cells with denser metachromatic granules."
  },
  {
    id: "basophil",
    name: "Basophil",
    category: "hematology",
    difficulty: 2,
    stain: "Wright–Giemsa",
    mag: "1000× oil",
    file: "Basophil.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Mast cell", "Dirty neutrophil", "Overstained lymphocyte"],
    blurb: "Dark purple granules that often obscure a lobated nucleus. Increased in CML and hypersensitivity. Mast cells are larger, tissue-based, and CD117/tryptase positive."
  },
  {
    id: "megakaryocyte",
    name: "Megakaryocyte",
    category: "hematology",
    difficulty: 2,
    stain: "Wright–Giemsa",
    mag: "400×",
    file: "Megakaryocyte.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Osteoclast", "Reed–Sternberg cell", "Multinucleated histiocyte"],
    blurb: "Huge marrow cell with a single multilobated nucleus and platelet-shedding cytoplasm. Osteoclasts have separate nuclei. RS cells live in lymph node, not as marrow giants with granular cytoplasm."
  },
  {
    id: "spherocytes",
    name: "Spherocytes",
    category: "hematology",
    difficulty: 3,
    stain: "Wright–Giemsa",
    mag: "1000× oil",
    file: "Spherocytes.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Microspherocytes of burns", "Overstained normal RBCs", "Liver-disease cells"],
    blurb: "Dense, round RBCs without central pallor. Hereditary spherocytosis vs immune hemolysis is a clinical call; both make spherocytes. Do not call them on a thick, dark smear."
  },
  {
    id: "target-cells",
    name: "Target cells (codocytes)",
    category: "hematology",
    difficulty: 2,
    stain: "Wright–Giemsa",
    mag: "1000× oil",
    file: "Target cells.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Sickle cell disease", "Artifact from slow drying", "Hemoglobin C crystals"],
    blurb: "Central bull's-eye of hemoglobin. Think hemoglobinopathy, liver disease, or asplenia. Slow-drying smears manufacture fake targets — look at a well-made area."
  },
  {
    id: "auer-rod",
    name: "Myeloblast with Auer rod",
    category: "hematology",
    difficulty: 4,
    stain: "Wright–Giemsa",
    mag: "1000× oil",
    file: "Myeloblast with Auer rod.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["ALL blast", "Reactive myelocyte", "Stain crystal"],
    blurb: "A needle-shaped azurophilic rod in a blast is myeloid, period — AML or high-grade MDS. Faggot cells (bundles of rods) scream APL. Do not wait on cytochemistry if you see one."
  },
  {
    id: "reed-sternberg",
    name: "Reed–Sternberg cell",
    category: "hematology",
    difficulty: 4,
    stain: "H&E",
    mag: "400×",
    file: "Hodgkin's lymphoma with RS cell 10x.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Megakaryocyte", "Viral immunoblast", "Anaplastic large-cell lymphoma"],
    blurb: "Giant binucleate cell with inclusion-like nucleoli — the owl-eye of Hodgkin lymphoma. CD15/CD30 positive, CD45/CD20 usually negative. ALCL and viral immunoblasts are the tissue lookalikes."
  },
  {
    id: "sperm",
    name: "Spermatozoa",
    category: "histology",
    difficulty: 1,
    stain: "Unstained / Pap / H&E",
    mag: "400–1000×",
    file: "Spermatozoa.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Trichomonas vaginalis", "Ciliated tuft (ciliocytophthoria)", "Fiber artifact"],
    blurb: "Head, midpiece, flagellum. In a Pap smear they are an unexpected guest. Trichomonas is pear-shaped with an undulating membrane, not a distinct head-tail sperm morphology."
  },
  {
    id: "hepatocytes",
    name: "Ground-glass hepatocytes",
    category: "histology",
    difficulty: 5,
    stain: "H&E",
    mag: "400×",
    file: "Ground glass hepatocytes high mag.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Lafora bodies", "Oncocytic change", "Glycogenated nuclei only"],
    blurb: "Finely granular pale-eosinophilic cytoplasm from HBsAg overload in chronic hepatitis B. Orcein or HBsAg IHC confirms. Lafora and oncocytes are the adult liver lookalikes."
  },
  {
    id: "adipose",
    name: "Adipose tissue",
    category: "histology",
    difficulty: 1,
    stain: "H&E",
    mag: "100–200×",
    file: "Adipose tissue.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Sebaceous gland", "Xanthoma", "Liposarcoma / atypical lipoma"],
    blurb: "Unilocular fat cells with peripheral nuclei. Sebaceous glands have bubbly cytoplasm and central nuclei. Architecture and atypia decide whether this is just fat or a lipomatous tumor."
  },
  {
    id: "alveoli",
    name: "Pulmonary alveoli",
    category: "histology",
    difficulty: 2,
    stain: "H&E",
    mag: "100–200×",
    file: "Alveoli.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Emphysema", "Thyroid follicles", "Adipose tissue"],
    blurb: "Thin septa lined by pneumocytes, with capillaries in the wall. Thyroid follicles have colloid. Emphysema is the same architecture with broken, enlarged spaces and lost surface area."
  },
  {
    id: "cardiac",
    name: "Cardiac muscle",
    category: "histology",
    difficulty: 2,
    stain: "H&E",
    mag: "200–400×",
    file: "Cardiac muscle.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Skeletal muscle", "Smooth muscle", "Nerve"],
    blurb: "Striated fibers with central nuclei and intercalated discs. Skeletal muscle nuclei are peripheral and there are no discs. Smooth muscle has no striations."
  },
  {
    id: "compact-bone",
    name: "Compact bone (osteons)",
    category: "histology",
    difficulty: 2,
    stain: "H&E / ground bone",
    mag: "100–200×",
    file: "Compact bone.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Cementum", "Dentin", "Pagetoid bone"],
    blurb: "Haversian canals wrapped in concentric lamellae, osteocytes in lacunae. Paget disease breaks the mosaic of those lamellae. Teeth tissues can mimic lamellae if the site is unknown."
  },
  {
    id: "epidermis",
    name: "Epidermis (skin)",
    category: "histology",
    difficulty: 1,
    stain: "H&E",
    mag: "100–200×",
    file: "Epidermis.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Squamous mucosa", "Urothelium", "Stratified squamous papilloma"],
    blurb: "Keratinizing stratified squamous epithelium with a granular layer and rete ridges. Mucosa usually lacks a granular layer and orthokeratin. Site and adnexa tell you it is skin."
  },
  {
    id: "glomerulus",
    name: "Renal glomerulus",
    category: "histology",
    difficulty: 2,
    stain: "H&E",
    mag: "200–400×",
    file: "Glomerulus.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Islet of Langerhans", "Nerve fascicle", "Capillary hemangioma"],
    blurb: "A capillary tuft inside Bowman space, with surrounding tubules. Islets lack a capsule space and sit in pancreas. Once you see the urinary space, you are in kidney."
  },
  {
    id: "goblet",
    name: "Goblet cells",
    category: "histology",
    difficulty: 2,
    stain: "H&E / PAS",
    mag: "200–400×",
    file: "Goblet cells.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Signet-ring carcinoma", "Paneth cells", "Mast cells"],
    blurb: "Mucin-filled epithelial cells with a compressed basal nucleus, PAS-positive. Signet-ring carcinoma infiltrates stroma and is atypical. Paneth cells have eosinophilic apical granules, not mucin."
  },
  {
    id: "cartilage",
    name: "Hyaline cartilage",
    category: "histology",
    difficulty: 2,
    stain: "H&E",
    mag: "100–200×",
    file: "Hyaline cartilage.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Elastic cartilage", "Fibrocartilage", "Chondrosarcoma"],
    blurb: "Glassy matrix with chondrocytes in lacunae, often in isogenous groups. Elastic cartilage needs an elastin stain. Atypia, permeation, and site decide neoplasia."
  },
  {
    id: "purkinje",
    name: "Cerebellar Purkinje cell",
    category: "histology",
    difficulty: 3,
    stain: "H&E / Nissl",
    mag: "200–400×",
    file: "Purkinje cell.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Betz cell (motor cortex)", "Anterior horn neuron", "Reactive astrocyte"],
    blurb: "A single row of huge flask-shaped neurons between molecular and granular layers of cerebellum. The dendritic tree fans into the molecular layer. Context is everything."
  },
  {
    id: "skeletal",
    name: "Skeletal muscle",
    category: "histology",
    difficulty: 2,
    stain: "H&E",
    mag: "200–400×",
    file: "Skeletal muscle.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Cardiac muscle", "Smooth muscle", "Nerve"],
    blurb: "Long striated fibers with peripheral nuclei. Cross-section shows polygonal fibers and a checkerboard of types on enzyme stains. Cardiac muscle keeps central nuclei and intercalated discs."
  },
  {
    id: "thyroid",
    name: "Thyroid follicles",
    category: "histology",
    difficulty: 2,
    stain: "H&E",
    mag: "100–200×",
    file: "Thyroid follicle.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Alveoli", "Colloid goiter vs normal", "Parathyroid"],
    blurb: "Follicles lined by cuboidal epithelium and filled with colloid, often with resorption scallops. Alveoli have no colloid. Parathyroid is sheeted chief cells without follicles."
  },
  {
    id: "islet",
    name: "Pancreatic islet of Langerhans",
    category: "histology",
    difficulty: 3,
    stain: "H&E",
    mag: "200–400×",
    file: "Human pancreatic islet.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Glomerulus", "Islet-cell tumor", "Lymphoid aggregate"],
    blurb: "Pale rounded cluster of endocrine cells dropped into exocrine acini. No Bowman space. A mass-forming, amyloid-rich, or infiltrative version is a neuroendocrine tumor."
  },
  {
    id: "respiratory",
    name: "Ciliated respiratory epithelium",
    category: "histology",
    difficulty: 2,
    stain: "H&E",
    mag: "200–400×",
    file: "Histology of pseudo stratified ciliates columnar epithelium.jpg",
    credit: "Wikimedia Commons",
    lookalikes: ["Fallopian tube epithelium", "Vas deferens", "Intestinal epithelium"],
    blurb: "Pseudostratified columnar epithelium with cilia and goblet cells. Tube epithelium is also ciliated but lacks goblets and sits on plicae. Gut has a brush border, not motile cilia."
  }
];
